export const FETCHING_NOTES = "FETCHING_NOTES";
export const FETCHING_NOTES_SUCCESS = "FETCHING_NOTES_SUCCESS";
export const FETCHING_NOTES_FAILED = "FETCHING_NOTES_FAILED";
export const FETCHING_NOTE = "FETCHING_NOTE";
export const FETCHING_NOTE_SUCCESS = "FETCHING_NOTE_SUCCESS";
export const FETCHING_NOTE_FAILED = "FETCHING_NOTE_FAILED";