export const FETCHING_TASKS = "FETCHING_TASKS";
export const FETCHING_TASKS_SUCCESS = "FETCHING_TASKS_SUCCESS";
export const FETCHING_TASKS_FAILED = "FETCHING_TASKS_FAILED";
export const FETCHING_TASK = "FETCHING_TASK";
export const FETCHING_TASK_SUCCESS = "FETCHING_TASK_SUCCESS";
export const FETCHING_TASK_FAILED = "FETCHING_TASK_FAILED";
